name: Check Links

on: 
  push:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Runs every Thursday at 20:23 GMT to avoid bit rot
    - cron: "23 20 * * 4"

env:
  USER_AGENT: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Link Checker
      uses: lycheeverse/lychee-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
        labels: report, automated issue
